[package]
name = "ark-mpc-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Cryptography === #
ark-bn254 = "0.5"
ark-ec = "0.5"
ark-mpc = { path = "../online-phase", features = ["test_helpers"] }
ark-mpc-offline = { path = "../offline-phase", features = ["parallel"] }

# === Runtime + Harness === #
clap = { version = "4.6.0", features = ["derive"] }
colored = "3"
env_logger = "0.11"
futures = "0.3"
inventory = "0.3"
tokio = "1.50"

# === Misc === #
dns-lookup = "3.0"
itertools = "0.14"
rand = "0.10"
tracing = "0.1"
